accounts:
  personal:
    email: aaroneden77@gmail.com
    display_name: Aaron Eden
    signature: |


      Aaron Eden
      (520)360-7193 (Mobile)

  bb:
    email: aaron@brainbridge.app
    display_name: Aaron Eden | Brain Bridge
    signature: |


      Aaron Eden
      Co-Founder, Brain Bridge
      Building a future where the fusion of AI and human insight elevates organizational knowledge into a strategic asset.
      (520)360-7193 (Mobile)

      FYI: I PROCESS MY EMAIL 2 TIMES DAILY. FOR ANYTHING MORE URGENT PLEASE CALL MY CELL.

  aitb:
    email: aaron@aitrailblazers.org
    display_name: Aaron Eden | AI Trailblazers
    signature: |


      Aaron Eden
      Co-Founder, AI Trailblazers
      Equipping, empowering and elevating our communities. AI for All.
      (520)360-7193
